// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf0DulFyteekZibEuMZNO7X26odt6iNOQ',
    appId: '1:379483053020:android:9ed01119b2fc6bb9580d19',
    messagingSenderId: '379483053020',
    projectId: 'recipely-a68b4',
    storageBucket: 'recipely-a68b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79j-Tb53nlXZg1hPJoNsN_8LFZ_jOIaQ',
    appId: '1:379483053020:ios:eeadbefab490c0ba580d19',
    messagingSenderId: '379483053020',
    projectId: 'recipely-a68b4',
    storageBucket: 'recipely-a68b4.firebasestorage.app',
    iosBundleId: 'com.example.recipelyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79j-Tb53nlXZg1hPJoNsN_8LFZ_jOIaQ',
    appId: '1:379483053020:ios:eeadbefab490c0ba580d19',
    messagingSenderId: '379483053020',
    projectId: 'recipely-a68b4',
    storageBucket: 'recipely-a68b4.firebasestorage.app',
    iosBundleId: 'com.example.recipelyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJuw1mmRkxubN5AOxaqI-1wnrcULAjJi0',
    appId: '1:379483053020:web:3621a12e9eb82f9f580d19',
    messagingSenderId: '379483053020',
    projectId: 'recipely-a68b4',
    authDomain: 'recipely-a68b4.firebaseapp.com',
    storageBucket: 'recipely-a68b4.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJuw1mmRkxubN5AOxaqI-1wnrcULAjJi0',
    appId: '1:379483053020:web:3621a12e9eb82f9f580d19',
    messagingSenderId: '379483053020',
    projectId: 'recipely-a68b4',
    authDomain: 'recipely-a68b4.firebaseapp.com',
    storageBucket: 'recipely-a68b4.firebasestorage.app',
  );

}